type = "web_pixel_extension"
name = "Deco personalization analytics"
runtime_context = "strict"
uid = "988d1058-d26b-824e-05a7-2dbac5c1dab723223ec5"

[customer_privacy]
analytics = true
marketing = false
preferences = false
sale_of_data = "disabled"

[settings]
type = "object"

[settings.fields.endpoint]
name = "Event endpoint"
description = "Store-scoped DecoAdmin Test event endpoint"
type = "single_line_text_field"
validations = [
  { name = "min", value = "1" }
]
