<script setup lang="ts">
import { Head, router, useForm } from '@inertiajs/vue3';
import { ref } from 'vue';
import AppLayout from '../../Layouts/AppLayout.vue';

type Log = { uuid: string; action: string; content: string | null; user: string; created_at: string };
type Row = { uuid: string; reference_no: string; title: string; description: string; category: string; priority: string; desired_date: string; status: string; submitter: string; assignee: string | null; created_at: string; can_accept: boolean; can_process: boolean; attachments: Array<{ uuid: string; name: string; url: string }>; progress_logs: Log[] };
type Page = { data: Row[]; current_page: number; last_page: number; total: number; prev_page_url: string | null; next_page_url: string | null };
const props = defineProps<{ scope: 'mine' | 'all'; canCreate: boolean; canManage: boolean; filters: { status: string; search: string }; options: { categories: string[]; priorities: string[] }; requests: Page }>();

const categoryLabels: Record<string, string> = { bug: '故障修复', feature: '功能开发', data: '数据支持', automation: '流程自动化', access: '权限申请', other: '其他' };
const priorityLabels: Record<string, string> = { urgent: '紧急', high: '高', medium: '中', low: '低' };
const statusLabels: Record<string, string> = { pending_approval: '待审批', approved: '待接受', rejected: '已驳回', assigned: '已接受', in_progress: '处理中', completed: '已完成' };
const createOpen = ref(false); const processOpen = ref(false); const selected = ref<Row | null>(null); const images = ref<File[]>([]); const accepting = ref<string | null>(null);
const filters = ref({ ...props.filters });
const form = useForm({ title: '', category: 'feature', priority: 'medium', desired_date: '', description: '', images: [] as File[] });
const progressForm = useForm({ action: 'progress' as 'progress' | 'complete', note: '' });
function applyFilters(): void { router.get('/technical-requests', Object.fromEntries(Object.entries(filters.value).filter(([, value]) => value)), { preserveState: true, replace: true }); }
function selectFiles(event: Event): void { const input = event.target as HTMLInputElement; images.value = Array.from(input.files ?? []).slice(0, 10); form.images = images.value; }
function pasteImages(event: ClipboardEvent): void { const files = Array.from(event.clipboardData?.items ?? []).filter(item => item.kind === 'file' && item.type.startsWith('image/')).map(item => item.getAsFile()).filter((file): file is File => Boolean(file)); if (!files.length) return; event.preventDefault(); images.value = [...images.value, ...files].slice(0, 10); form.images = images.value; }
function submit(): void { form.post('/technical-requests', { forceFormData: true, onSuccess: () => { createOpen.value = false; images.value = []; form.reset(); form.category = 'feature'; form.priority = 'medium'; } }); }
function accept(row: Row): void { accepting.value = row.uuid; router.post(`/technical-requests/${row.uuid}/accept`, {}, { preserveScroll: true, onFinish: () => { accepting.value = null; } }); }
function openProcess(row: Row): void { selected.value = row; processOpen.value = true; progressForm.reset(); }
function saveProgress(action: 'progress' | 'complete'): void { if (!selected.value) return; progressForm.action = action; progressForm.put(`/technical-requests/${selected.value.uuid}/progress`, { preserveScroll: true, onSuccess: () => { processOpen.value = false; selected.value = null; } }); }
</script>

<template>
    <Head title="技术需求" />
    <AppLayout :breadcrumbs="[{ label: '个人' }, { label: '需求和报销' }, { label: '技术需求' }]">
        <main class="mx-auto w-full max-w-[1500px] space-y-5">
            <header class="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><span class="rounded-full bg-violet-50 px-3 py-1 text-xs font-semibold text-violet-700">{{ scope === 'all' ? '全部技术需求' : '我的技术需求' }}</span><h1 class="mt-3 text-2xl font-bold text-slate-950">技术需求</h1><p class="mt-1.5 text-sm text-slate-500">提交系统问题、功能开发、数据和自动化需求，审批通过后由开发人员处理。</p></div><button v-if="canCreate" class="h-11 rounded-xl bg-violet-600 px-5 text-sm font-semibold text-white shadow-sm hover:bg-violet-700" @click="createOpen = true">+ 新建技术需求</button></header>
            <form class="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-[minmax(220px,1fr)_180px_auto]" @submit.prevent="applyFilters"><input v-model="filters.search" placeholder="搜索编号、标题或描述" class="h-11 rounded-xl border-slate-200 text-sm" /><select v-model="filters.status" class="h-11 rounded-xl border-slate-200 text-sm"><option value="">全部状态</option><option v-for="(label, value) in statusLabels" :key="value" :value="value">{{ label }}</option></select><button class="h-11 rounded-xl bg-slate-900 px-5 text-sm font-semibold text-white">筛选</button></form>
            <section class="space-y-3"><article v-for="row in requests.data" :key="row.uuid" class="grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:grid-cols-[minmax(280px,1.4fr)_150px_160px_130px_auto] lg:items-center"><div><div class="flex flex-wrap items-center gap-2"><span class="font-mono text-xs font-semibold text-slate-400">{{ row.reference_no }}</span><span class="rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-600">{{ categoryLabels[row.category] }}</span></div><h2 class="mt-2 font-semibold text-slate-900">{{ row.title }}</h2><p class="mt-1 line-clamp-2 text-sm leading-5 text-slate-500">{{ row.description }}</p><div v-if="row.attachments.length" class="mt-3 flex gap-2"><a v-for="file in row.attachments.slice(0, 4)" :key="file.uuid" :href="file.url" target="_blank"><img :src="file.url" :alt="file.name" class="h-11 w-14 rounded-lg border border-slate-200 object-cover" /></a></div></div><div class="text-sm"><p class="text-xs text-slate-400">提交人</p><p class="mt-1 font-medium text-slate-700">{{ row.submitter }}</p><p class="mt-3 text-xs text-slate-400">期望日期</p><p class="mt-1 text-slate-700">{{ row.desired_date }}</p></div><div><span class="rounded-full bg-violet-50 px-2.5 py-1 text-xs font-semibold text-violet-700">{{ priorityLabels[row.priority] }}优先级</span><p class="mt-3 text-xs text-slate-400">处理人</p><p class="mt-1 text-sm font-medium" :class="row.assignee ? 'text-slate-700' : 'text-amber-600'">{{ row.assignee || '待接受' }}</p></div><div><span class="rounded-full px-3 py-1.5 text-xs font-semibold" :class="row.status === 'completed' ? 'bg-emerald-50 text-emerald-700' : row.status === 'rejected' ? 'bg-rose-50 text-rose-700' : row.status === 'pending_approval' ? 'bg-amber-50 text-amber-700' : 'bg-blue-50 text-blue-700'">{{ statusLabels[row.status] }}</span><p class="mt-2 text-xs text-slate-400">{{ row.created_at }}</p></div><div v-if="canManage" class="text-right"><button v-if="row.can_accept" class="rounded-xl border border-violet-200 bg-violet-50 px-4 py-2 text-sm font-semibold text-violet-700" :disabled="accepting !== null" @click="accept(row)">{{ accepting === row.uuid ? '接受中…' : '接受' }}</button><button v-else-if="row.can_process" class="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white" @click="openProcess(row)">处理</button></div></article><div v-if="!requests.data.length" class="rounded-2xl border border-dashed border-slate-300 bg-white py-16 text-center text-sm text-slate-400">暂无技术需求</div></section>
            <footer v-if="requests.last_page > 1" class="flex justify-center gap-2"><button :disabled="!requests.prev_page_url" class="rounded-lg border px-4 py-2 text-sm disabled:opacity-40" @click="requests.prev_page_url && router.get(requests.prev_page_url)">上一页</button><span class="px-3 py-2 text-sm text-slate-500">{{ requests.current_page }} / {{ requests.last_page }}</span><button :disabled="!requests.next_page_url" class="rounded-lg border px-4 py-2 text-sm disabled:opacity-40" @click="requests.next_page_url && router.get(requests.next_page_url)">下一页</button></footer>
        </main>
        <Teleport to="body"><dialog :open="createOpen" class="fixed inset-0 z-50 m-0 h-full w-full max-w-none bg-slate-950/45 p-4" @click.self="createOpen = false"><form class="mx-auto mt-[5vh] max-h-[90vh] max-w-2xl overflow-y-auto rounded-3xl bg-white p-7 shadow-2xl" @submit.prevent="submit"><div class="flex justify-between"><div><h2 class="text-xl font-bold">新建技术需求</h2><p class="mt-1 text-sm text-slate-500">描述问题、目标和期望完成时间。</p></div><button type="button" class="text-2xl text-slate-400" @click="createOpen = false">×</button></div><div class="mt-6 grid gap-4 sm:grid-cols-2"><label class="text-sm font-semibold text-slate-700 sm:col-span-2">需求标题<input v-model="form.title" required maxlength="180" class="mt-2 h-11 w-full rounded-xl border-slate-200" placeholder="一句话说明需要解决的问题" /></label><label class="text-sm font-semibold text-slate-700">需求类型<select v-model="form.category" class="mt-2 h-11 w-full rounded-xl border-slate-200"><option v-for="item in options.categories" :key="item" :value="item">{{ categoryLabels[item] }}</option></select></label><label class="text-sm font-semibold text-slate-700">优先级<select v-model="form.priority" class="mt-2 h-11 w-full rounded-xl border-slate-200"><option v-for="item in options.priorities" :key="item" :value="item">{{ priorityLabels[item] }}</option></select></label><label class="text-sm font-semibold text-slate-700 sm:col-span-2">期望完成日期<input v-model="form.desired_date" required type="date" class="mt-2 h-11 w-full rounded-xl border-slate-200" /></label><label class="text-sm font-semibold text-slate-700 sm:col-span-2">需求描述<textarea v-model="form.description" required rows="7" maxlength="5000" class="mt-2 w-full rounded-xl border-slate-200" placeholder="请说明现状、期望结果、复现步骤或验收标准" @paste="pasteImages"></textarea></label><label class="text-sm font-semibold text-slate-700 sm:col-span-2">截图或附件<input type="file" multiple accept="image/*" class="mt-2 block w-full text-sm" @change="selectFiles" /><span class="mt-1 block text-xs font-normal text-slate-400">可直接在描述框粘贴截图，最多 10 张。</span></label></div><p v-if="form.hasErrors" class="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{{ Object.values(form.errors).join('；') }}</p><div class="mt-6 flex justify-end gap-3"><button type="button" class="h-11 rounded-xl border px-5 text-sm font-semibold" @click="createOpen = false">取消</button><button class="h-11 rounded-xl bg-violet-600 px-5 text-sm font-semibold text-white">提交审批</button></div></form></dialog>
        <dialog :open="processOpen" class="fixed inset-0 z-50 m-0 h-full w-full max-w-none bg-slate-950/45 p-4" @click.self="processOpen = false"><form v-if="selected" class="mx-auto mt-[7vh] max-h-[86vh] max-w-xl overflow-y-auto rounded-3xl bg-white p-7 shadow-2xl" @submit.prevent="saveProgress('progress')"><div class="flex justify-between"><div><p class="font-mono text-xs text-violet-600">{{ selected.reference_no }}</p><h2 class="mt-1 text-xl font-bold">{{ selected.title }}</h2></div><button type="button" class="text-2xl text-slate-400" @click="processOpen = false">×</button></div><div class="mt-6 space-y-3"><div v-for="log in selected.progress_logs" :key="log.uuid" class="rounded-xl bg-slate-50 p-3"><div class="flex justify-between text-xs text-slate-400"><span>{{ log.user }} · {{ log.action }}</span><span>{{ log.created_at }}</span></div><p v-if="log.content" class="mt-2 text-sm text-slate-700">{{ log.content }}</p></div></div><label class="mt-5 block text-sm font-semibold text-slate-700">进展记录<textarea v-model="progressForm.note" rows="5" maxlength="3000" class="mt-2 w-full rounded-xl border-slate-200" placeholder="填写已完成内容、链接或遇到的问题"></textarea></label><p v-if="progressForm.hasErrors" class="mt-3 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{{ Object.values(progressForm.errors).join('；') }}</p><div class="mt-6 flex justify-end gap-3"><button type="submit" class="h-11 rounded-xl border border-violet-200 bg-violet-50 px-5 text-sm font-semibold text-violet-700">提交进展</button><button type="button" class="h-11 rounded-xl bg-emerald-600 px-5 text-sm font-semibold text-white" @click="saveProgress('complete')">完成需求</button></div></form></dialog></Teleport>
    </AppLayout>
</template>
