<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>Deco Referral · 推广者门户</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f5f7f8;color:#152a2a;font:15px/1.65 system-ui,sans-serif}header,main{max-width:1080px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #dce4e3}h1{font-size:28px;line-height:1.3}h2{font-size:18px;margin:0 0 16px}p{color:#526663}a{color:#087361}section,.card{padding:24px;background:white;border:1px solid #dce4e3;border-radius:16px;margin-bottom:20px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:20px}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px}.metrics strong{display:block;font-size:24px}.label{font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:#087361}label{display:block;margin:12px 0}input,select,textarea{width:100%;padding:11px;border:1px solid #bdccca;border-radius:8px;font:inherit}input[type=checkbox]{width:auto}button,.button{display:inline-block;padding:11px 18px;border:0;background:#087361;border-radius:8px;color:white;font:inherit;cursor:pointer}button.secondary{background:#e9f2ef;color:#087361}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;padding:12px 8px;border-bottom:1px solid #e5ecea}th{color:#5d706d}code{word-break:break-all}.notice{padding:14px 18px;border-radius:10px;background:#e8f5ed;margin-bottom:20px}.error{background:#fff0ec;color:#933e22}.scroll{overflow:auto}nav a{margin-right:16px}small{color:#6b7d79}footer{text-align:center;color:#6b7d79;padding:30px}
</style></head><body>
<header><a href="/referral-portal"><b>DECO REFERRAL</b></a>@if($page==='dashboard')<form method="post" action="/referral-portal/logout">@csrf<button class="secondary">退出登录</button></form>@endif</header>
<main>
@if(session('portal_message'))<div class="notice">{{session('portal_message')}}</div>@endif
@if($errors->any())<div class="notice error">@foreach($errors->all() as $error)<div>{{$error}}</div>@endforeach</div>@endif
@if($page==='welcome')
<p class="label">{{$store->name}}</p><h1>分享好产品，查看你的推广成果。</h1><p>申请加入推广计划，获批后即可获取专属链接、优惠码，并查看佣金和付款记录。</p>
<div class="grid"><section><h2>申请加入</h2><form method="post" action="/referral-portal/apply">@csrf
<label>推广计划<select name="program" required>@foreach($programs as $program)<option value="{{$program->public_id}}">{{$program->name}}</option>@endforeach</select></label>
<label>姓名<input name="name" required maxlength="120"></label><label>邮箱<input name="email" type="email" required maxlength="254"></label><label>国家 / 地区<input name="country" maxlength="80"></label><label>网站或社交主页<input name="website" type="url" placeholder="https://"></label><label>推广方式<textarea name="method" maxlength="1000"></textarea></label><label>备注<textarea name="notes" maxlength="2000">{{old('notes')}}</textarea></label><label><input type="checkbox" name="terms" value="1" required> 我确认申请资料准确，同意由店铺审核该申请。</label><button @disabled($programs->isEmpty())>提交申请</button></form></section>
<section><h2>已获批准？</h2><p>通过邮箱获取一次性登录链接，有效期 15 分钟。</p><form method="post" action="/referral-portal/request-login">@csrf<label>推广计划<select name="program" required>@foreach($loginPrograms as $program)<option value="{{$program->public_id}}">{{$program->name}}</option>@endforeach</select></label><label>邮箱<input name="email" type="email" required></label><button @disabled($loginPrograms->isEmpty())>发送登录链接</button></form></section></div>
@elseif($page==='invitation')
<section style="max-width:560px;margin:40px auto"><h1>加入推广计划</h1><p>此邀请七天内有效，仅可使用一次；接受后仍须店铺审核。</p><form method="post" action="/referral-portal/invitation">@csrf<input type="hidden" name="token" id="invitation-token" value="{{old('token')}}"><label>网站或社交主页<input name="website" type="url" maxlength="500" value="{{old('website')}}"></label><label>补充说明<textarea name="notes" maxlength="2000">{{old('notes')}}</textarea></label><label><input type="checkbox" name="terms" value="1" required> 我确认资料准确，同意由店铺审核申请。</label><button id="accept-invitation" disabled>接受邀请并提交审核</button></form><p id="invitation-error"></p></section>
<script>const token=new URLSearchParams(location.hash.slice(1)).get('token')||document.getElementById('invitation-token').value||'';history.replaceState(null,'',location.pathname);if(/^[a-f0-9]{64}$/.test(token)){document.getElementById('invitation-token').value=token;document.getElementById('accept-invitation').disabled=false;}else document.getElementById('invitation-error').textContent='请使用店铺提供的完整邀请链接。';</script>
@elseif($page==='login')
<section style="max-width:520px;margin:40px auto"><h1>安全登录</h1><p>确认继续后，这条一次性登录链接即被使用。</p><form method="post" action="/referral-portal/session">@csrf<input type="hidden" name="token" id="login-token"><button id="continue-login" disabled>继续登录</button></form><p id="login-error"></p></section>
<script>const value=new URLSearchParams(location.hash.slice(1)).get('token')||'';history.replaceState(null,'',location.pathname);if(/^[a-f0-9]{64}$/.test(value)){document.getElementById('login-token').value=value;document.getElementById('continue-login').disabled=false;}else{document.getElementById('login-error').textContent='请从邮件中的登录链接进入。';}</script>
@else
@php($statusLabel=fn($s)=>['pending'=>'待确认','available'=>'可结算','reserved'=>'结算中','settled'=>'已结算','superseded'=>'归属已更正','paid'=>'已付款','approved'=>'已通过','review'=>'待审核','rejected'=>'已拒绝','refunded'=>'已退款','partially_refunded'=>'部分退款','cancelled'=>'已取消'][$s]??$s)
@php($entryLabel=fn($s)=>['commission_accrual'=>'订单佣金','refund_adjustment'=>'退款扣回','cancellation_adjustment'=>'取消扣回','manual_accrual'=>'人工归因佣金','manual_refund'=>'人工归因退款扣回','manual_adjustment'=>'人工调整','payout_settlement'=>'付款结算','reassignment_out'=>'归属更正扣回'][$s]??$s)
@php($isAdvocate=$member->program->type->value==='advocate')
@php($money=fn($amount)=>\App\Domain\ReferralAffiliate\Support\Money::decimal((int)$amount,$store->currency))
<p class="label">{{$store->name}} · {{$member->program->name}}</p><h1>你好，{{$member->promoter->display_name}}</h1><nav><a href="#links">推广链接</a><a href="#orders">推荐订单</a>@if($isAdvocate)<a href="#rewards">推荐奖励</a>@else<a href="#ledger">佣金</a><a href="#payouts">付款</a>@endif<a href="#assets">素材</a><a href="#profile">个人资料</a></nav>
<div class="metrics" style="margin:24px 0">@if(!$isAdvocate)@foreach(['pending'=>'待确认','available'=>'可用余额','reserved'=>'结算中'] as $key=>$label)<div class="card"><small>{{$label}} · {{$store->currency}}</small><strong>{{$balances[$key]??$money(0)}}</strong></div>@endforeach@endif<div class="card"><small>点击数</small><strong>{{$clicks}}</strong></div></div>
<section id="links"><h2>专属推广链接与优惠码</h2>@if($member->link)<p><a id="referral-link" href="{{url('/r/'.$member->link->public_id)}}">{{url('/r/'.$member->link->public_id)}}</a></p><button type="button" class="secondary" onclick="navigator.clipboard.writeText(document.getElementById('referral-link').href).then(()=>this.textContent='已复制')">复制链接</button><form id="deep-link-form"><label>店内商品或页面路径<input name="path" value="/" maxlength="1000" placeholder="/products/example"></label><label>来源标签<input name="source" maxlength="100" placeholder="例如 instagram"></label><button type="submit">生成推广深链</button></form><p id="deep-link-error" role="status"></p><canvas id="referral-qr" aria-label="推广链接二维码"></canvas><button type="button" class="secondary" id="download-qr">下载二维码</button><script src="/referral-portal/portal.js" defer></script>@endif
@if($member->coupon)<p>优惠码：<code>{{$member->coupon->code}}</code> · {{['active'=>'已生效','disabled'=>'已停用','scheduled'=>'未到生效时间','sync_pending'=>'等待同步','enable_pending'=>'等待启用','disable_pending'=>'等待停用'][$member->coupon->status]??'待确认'}}</p>@endif</section>
@if($member->program->type->value==='advocate')<section id="rewards"><h2>我的推荐奖励</h2><p>奖励为本人专用、一次性优惠码。现金佣金不适用于此顾客推荐计划。</p>@forelse($rewards as $reward)<p><b>{{$reward['code']??'等待奖励发放'}}</b> · {{['pending'=>'等待核验 / 等待期','issued'=>'可使用','redeemed'=>'已使用','expired'=>'已过期','revoked'=>'已撤销','revoke_pending'=>'撤销处理中','failed'=>'同步待处理'][$reward['status']]??'处理中'}} @if($reward['threshold']) · 累计 {{$reward['threshold']}} 单奖励 @endif @if($reward['expires_at']) · 有效期至 {{$reward['expires_at']}} @endif</p>@empty<p>好友完成符合条件的订单后，奖励会显示在这里。</p>@endforelse</section>@endif
<section id="orders"><h2>推荐订单</h2><div class="scroll"><table><thead><tr><th>记录</th><th>时间</th><th>状态</th><th>佣金 {{$store->currency}}</th><th>扣回</th></tr></thead><tbody>@forelse($conversions as $conversion)<tr><td>{{substr($conversion->public_id,-8)}}</td><td>{{$conversion->ordered_at->format('Y-m-d')}}</td><td>{{$statusLabel($conversion->status)}}</td><td>{{$money($conversion->commission_minor)}}</td><td>{{$money($conversion->reversed_minor)}}</td></tr>@empty<tr><td colspan="5">暂无推荐订单。</td></tr>@endforelse</tbody></table></div><p>@if($conversions->previousPageUrl())<a href="{{$conversions->previousPageUrl()}}">上一页</a>@endif @if($conversions->nextPageUrl())<a href="{{$conversions->nextPageUrl()}}">下一页</a>@endif</p></section>
@if(!$isAdvocate)<section id="ledger"><h2>近期佣金分录</h2><div class="scroll"><table><thead><tr><th>时间</th><th>类型</th><th>状态</th><th>金额 {{$store->currency}}</th></tr></thead><tbody>@forelse($entries as $entry)<tr><td>{{$entry->created_at->format('Y-m-d')}}</td><td>{{$entryLabel($entry->type)}}</td><td>{{$statusLabel($entry->status)}}</td><td>{{$money($entry->amount_minor)}}</td></tr>@empty<tr><td colspan="4">暂无分录。</td></tr>@endforelse</tbody></table></div></section>
<section id="payouts"><h2>付款记录</h2>@forelse($payouts as $payout)<p>{{$payout->created_at->format('Y-m-d')}} · {{$money($payout->amount_minor)}} {{$store->currency}} · {{$statusLabel($payout->status)}}</p>@empty<p>暂无付款记录。</p>@endforelse</section>
@endif
<section id="assets"><h2>推广素材</h2>@forelse($assets as $asset)<p><a href="/referral-portal/assets/{{$asset->public_id}}">{{$asset->title}}</a></p>@empty<p>店铺尚未上传素材。</p>@endforelse</section>
<section id="profile"><h2>个人资料</h2><p>邮箱：{{$member->promoter->email_encrypted}}</p>@if(!$isAdvocate)<p>付款资料更新需要在最近 15 分钟内通过邮件登录验证。</p><form method="post" action="/referral-portal/profile">@csrf<label>国家 / 地区<input name="country" value="{{old('country',data_get($member->promoter->profile_encrypted,'country'))}}"></label><label>付款偏好<select name="payment_method"><option value="paypal" @selected(old('payment_method',data_get($member->promoter->profile_encrypted,'payment_method','paypal'))==='paypal')>PayPal</option><option value="bank" @selected(old('payment_method',data_get($member->promoter->profile_encrypted,'payment_method','paypal'))==='bank')>银行</option><option value="other" @selected(old('payment_method',data_get($member->promoter->profile_encrypted,'payment_method','paypal'))==='other')>其他</option></select></label><label>收款资料<textarea name="payment_reference" required maxlength="500">{{old('payment_reference',data_get($member->promoter->profile_encrypted,'payment_reference'))}}</textarea></label><button>保存资料</button></form>@endif</section>
@endif
</main><footer>Deco Referral · 你的推广数据仅在获授权的店铺范围内展示</footer></body></html>
