client_id = "52f415f03423fe1f1838dcfa7a0fca9a"
name = "decoadmin-development"
application_url = "https://admin.decomkt.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-07"

[access_scopes]
scopes = "read_customers,read_inventory,read_locations,read_orders,read_products,read_reports"
optional_scopes = []
use_legacy_install_flow = true

[auth]
redirect_urls = ["https://admin.decomkt.com/shopify/oauth/callback"]
