client_id = "44ddcba51c2e4f3eec425aae1d2cbe22"
name = "Deco Referral Test"
application_url = "https://testadmin.decomkt.com/shopify-app/referral"
embedded = true

[access_scopes]
scopes = "read_orders,read_customers,read_products,write_discounts"
use_legacy_install_flow = false

[auth]
redirect_urls = ["https://testadmin.decomkt.com/shopify-app/referral"]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["orders/paid", "orders/cancelled", "refunds/create", "app/uninstalled", "app/scopes_update"]
uri = "https://testadmin.decomkt.com/api/shopify-app/referral/webhooks"
