<script setup lang="ts">
import { Head, Link } from '@inertiajs/vue3';
import AppLayout from '../../Layouts/AppLayout.vue';
interface Level { id:number; available:number; inventory_item:{id:number;sku:string|null;variant:{title:string;product:{title:string}|null}|null} }
interface Location { id:number;name:string;shopify_location_id:string;address:Record<string,string|null>|null;active:boolean;synced_at:string|null;inventory_levels:Level[] }
const props=defineProps<{location:Location}>();
const total=()=>props.location.inventory_levels.reduce((sum,item)=>sum+item.available,0);
const address=()=>props.location.address ? [props.location.address.address1,props.location.address.address2,props.location.address.city,props.location.address.province,props.location.address.zip,props.location.address.country].filter(Boolean).join(' · ') : '未提供地址';
</script>
<template><Head :title="location.name"/><AppLayout :breadcrumbs="[{label:'业务中心'},{label:'地点管理',href:'/locations'},{label:location.name}]"><div class="mx-auto max-w-6xl space-y-6"><Link href="/locations" class="text-sm font-semibold text-slate-500">← 返回地点列表</Link><header><div class="flex items-center gap-3"><h1 class="text-3xl font-semibold text-slate-950">{{location.name}}</h1><span class="rounded-full px-2.5 py-1 text-xs font-semibold" :class="location.active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'">{{location.active?'启用':'停用'}}</span></div><p class="mt-2 text-sm text-slate-500">{{address()}}</p></header><section class="grid gap-4 sm:grid-cols-3"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs text-slate-400">库存项目</p><p class="mt-2 text-2xl font-semibold">{{location.inventory_levels.length}}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs text-slate-400">可用库存</p><p class="mt-2 text-2xl font-semibold">{{total()}}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs text-slate-400">Shopify Location ID</p><p class="mt-2 break-all font-mono text-sm font-semibold">{{location.shopify_location_id}}</p></div></section><section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-6 py-5"><h2 class="font-semibold text-slate-900">地点库存明细</h2></div><div v-if="location.inventory_levels.length" class="divide-y divide-slate-100"><article v-for="level in location.inventory_levels" :key="level.id" class="flex items-center justify-between gap-4 px-6 py-5"><div><Link :href="`/inventory/${level.inventory_item.id}`" class="font-semibold text-slate-900 hover:text-emerald-700">{{level.inventory_item.variant?.product?.title||'未关联商品'}}</Link><p class="mt-1 text-xs text-slate-400">{{level.inventory_item.variant?.title||'未知变体'}} · SKU {{level.inventory_item.sku||'—'}}</p></div><p class="text-2xl font-semibold text-slate-950">{{level.available}}</p></article></div><p v-else class="px-6 py-10 text-center text-sm text-slate-400">此地点暂无库存项目。</p></section></div></AppLayout></template>
