<script setup lang="ts">
import { Head, Link, router, useForm } from '@inertiajs/vue3';
import { computed, ref } from 'vue';
import AppLayout from '../../Layouts/AppLayout.vue';
interface Row { public_id:string; label:string; status:string; created_at:string; amount?:string; currency?:string; base?:string; reversed?:string; reason?:string; source?:string; is_test?:boolean; available_at?:string; reference?:string; has_proof?:boolean; details?:unknown }
const props=defineProps<{organization:{id:number;name:string};store:{id:number;name:string;currency:string};section:string;rows:{data:Row[];links:{url:string|null;label:string;active:boolean}[];total:number};permissions:Record<string,boolean>;memberships:{public_id:string;name:string}[];totals:Record<string,string|number>;filters:{status:string|null}}>();
const assigning=ref<Row|null>(null);
const assignForm=useForm({membership:'',reason:'',request_id:''});
const names:Record<string,string>={conversions:'推荐订单',commissions:'佣金账本',payouts:'结算中心',risks:'风险审查',reports:'推广报表',rewards:'顾客奖励'};
const title=computed(()=>names[props.section]);
const base=`/organizations/${props.organization.id}/stores/${props.store.id}/affiliate`;
const statusLabel=(s:string)=>(({issued:'已发放',redeemed:'已使用',expired:'已过期',revoked:'已撤销',revoke_pending:'撤销处理中',pending:'待确认',available:'可结算',reserved:'已占用',settled:'已结算',draft:'待付款',paid:'已记录付款',cancelled:'已取消',failed:'失败',approved:'已通过',rejected:'已拒绝',review:'需审核',open:'待审核',reviewing:'审核中',dismissed:'已排除',unattributed:'未归因',partially_refunded:'部分退款',refunded:'已全额退款'} as Record<string,string>)[s]??s);
const typeLabel=(s:string)=>(({commission_accrual:'订单佣金',refund_adjustment:'退款扣回',cancellation_adjustment:'取消扣回',manual_adjustment:'人工调整',payout_settlement:'付款结算',same_email_hash:'买家与推广者邮箱相同',self_customer_id:'同一顾客自购',multiple_coupon_conflict:'多个推广优惠码冲突'} as Record<string,string>)[s]??s);
const sync=useForm({order_id:''});
const newRequestId=()=>crypto.randomUUID();
const adjustment=useForm({membership:props.memberships[0]?.public_id??'',amount:'',reason:'',request_id:newRequestId()});
const payout=useForm({minimum:'50',cutoff:new Date().toISOString()});
const selected=ref<Row|null>(null);
const action=useForm({action:'paid',reference:'',reason:'',proof:null as File|null});
const showAdjust=ref(false);const showCreate=ref(false);
const filter=ref(props.filters.status??'');
function applyFilter(){router.get(`${base}/finance/${props.section}`,{status:filter.value||undefined},{preserveState:true});}
function submitAction(){if(!selected.value)return;const url=props.section==='risks'?`${base}/finance/risks/${selected.value.public_id}`:`${base}/finance/payouts/${selected.value.public_id}`;action.post(url,{onSuccess:()=>{selected.value=null;action.reset();}});}
function openAction(row:Row,value:string){selected.value=row;action.action=value;action.reference='';action.reason='';action.proof=null;}
</script>
<template>
 <Head :title="title"/>
 <AppLayout :breadcrumbs="[{label:'推荐与联盟',href:base},{label:title}]">
  <div class="space-y-6">
   <header class="flex flex-wrap items-center justify-between gap-4"><div><p class="text-xs font-semibold uppercase text-emerald-700">{{store.name}}</p><h1 class="mt-1 text-2xl font-bold text-slate-900">{{title}}</h1><p class="mt-2 text-sm text-slate-500">按店铺独立记录，每笔金额均可追溯。</p></div>
    <div class="flex gap-2"><button v-if="section==='commissions'&&permissions['commissions.adjust']" class="rounded-xl bg-emerald-700 px-4 py-2 text-sm text-white" @click="showAdjust=!showAdjust">追加调整</button><button v-if="section==='commissions'&&permissions['commissions.approve']" class="rounded-xl border px-4 py-2 text-sm" @click="router.post(`${base}/finance/release`)">释放到期佣金</button><button v-if="section==='payouts'&&permissions['payouts.create']" class="rounded-xl bg-emerald-700 px-4 py-2 text-sm text-white" @click="showCreate=!showCreate">新建结算批次</button></div>
   </header>
   <form v-if="section==='conversions'&&permissions['conversions.override']" class="flex flex-wrap gap-3 rounded-2xl border bg-white p-4" @submit.prevent="sync.post(`${base}/finance/reconcile`)"><input v-model="sync.order_id" placeholder="Shopify 订单 ID，留空核对最近三天" class="min-w-72 flex-1 rounded-xl border-slate-300"><button :disabled="sync.processing" class="rounded-xl bg-slate-900 px-4 py-2 text-white">核对订单</button><p v-for="error in sync.errors" :key="error" class="text-sm text-red-600">{{error}}</p></form>
   <a v-if="section==='reports' && permissions['reports.export']" :href="`${base}/reports/export`" class="inline-flex rounded-xl border bg-white px-4 py-2 text-emerald-700">导出报表</a>
   <div v-if="section==='reports'" class="grid gap-4 sm:grid-cols-4"><div v-for="(label,key) in {orders:'推荐订单数',net_sales:'推荐商品净额',commission:'产生佣金',reversed:'累计扣回'}" :key="key" class="rounded-2xl border bg-white p-5"><p class="text-sm text-slate-500">{{label}}</p><p class="mt-2 text-2xl font-bold">{{totals[key]??0}} <small v-if="key!=='orders'" class="text-xs">{{store.currency}}</small></p></div></div>
   <form v-if="showAdjust" class="grid gap-4 rounded-2xl border bg-white p-5 sm:grid-cols-2" @submit.prevent="adjustment.post(`${base}/finance/adjust`,{onSuccess:()=>{showAdjust=false;adjustment.reset('amount','reason');adjustment.request_id=newRequestId();}})"><label class="text-sm">推广者<select v-model="adjustment.membership" class="mt-1 w-full rounded-xl border-slate-300"><option v-for="m in memberships" :key="m.public_id" :value="m.public_id">{{m.name}}</option></select></label><label class="text-sm">调整金额（{{store.currency}}，扣减填写负数）<input v-model="adjustment.amount" inputmode="decimal" required class="mt-1 w-full rounded-xl border-slate-300"></label><label class="text-sm sm:col-span-2">调整原因<textarea v-model="adjustment.reason" required minlength="3" class="mt-1 w-full rounded-xl border-slate-300"/></label><p v-for="error in adjustment.errors" :key="error" class="text-sm text-red-600">{{error}}</p><button :disabled="adjustment.processing" class="rounded-xl bg-emerald-700 px-4 py-2 text-white">保存调整分录</button></form>
   <form v-if="showCreate" class="flex flex-wrap items-end gap-4 rounded-2xl border bg-white p-5" @submit.prevent="payout.cutoff=new Date().toISOString();payout.post(`${base}/finance/payouts`,{onSuccess:()=>showCreate=false})"><label class="text-sm">最低付款金额（{{store.currency}}）<input v-model="payout.minimum" inputmode="decimal" required class="mt-1 block rounded-xl border-slate-300"></label><p class="text-sm text-slate-500">汇总当前可用佣金，先抵扣负余额；创建后占用分录。</p><button :disabled="payout.processing" class="rounded-xl bg-emerald-700 px-4 py-2 text-white">创建并占用</button><p v-for="error in payout.errors" :key="error" class="text-sm text-red-600">{{error}}</p></form>
   <div class="flex gap-2"><select v-model="filter" class="rounded-xl border-slate-300 text-sm" @change="applyFilter"><option value="">全部状态</option><option v-for="s in ['pending','available','reserved','settled','draft','paid','cancelled','approved','review','open','rejected','refunded','partially_refunded','unattributed']" :key="s" :value="s">{{statusLabel(s)}}</option></select><span class="self-center text-sm text-slate-500">共 {{rows.total}} 条</span></div>
   <div class="overflow-x-auto rounded-2xl border bg-white"><table class="w-full min-w-[820px] text-left text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4">记录</th><th class="p-4">时间</th><th class="p-4">状态</th><th class="p-4">金额</th><th class="p-4">说明 / 操作</th></tr></thead><tbody><tr v-for="row in rows.data" :key="row.public_id" class="border-t"><td class="p-4 font-medium">{{typeLabel(row.label)}}<span v-if="row.is_test" class="ml-2 rounded bg-amber-50 px-2 py-1 text-xs text-amber-700">测试</span></td><td class="p-4 text-slate-500">{{new Date(row.created_at).toLocaleString()}}</td><td class="p-4">{{statusLabel(row.status)}}</td><td class="p-4 tabular-nums">{{row.amount??'—'}} {{row.currency}}<p v-if="row.base" class="text-xs text-slate-500">计佣基数 {{row.base}} · 已扣回 {{row.reversed}}</p></td><td class="p-4"><p class="max-w-xs break-words text-xs text-slate-500">{{row.reason||row.reference}}</p><details v-if="row.details" class="mt-2"><summary class="cursor-pointer text-emerald-700">查看依据</summary><pre class="mt-2 max-h-64 max-w-md overflow-auto whitespace-pre-wrap rounded bg-slate-50 p-3 text-xs">{{JSON.stringify(row.details,null,2)}}</pre></details><button v-if="section==='conversions' && row.status==='unattributed' && permissions['conversions.override']" class="mt-2 text-emerald-700" @click="assigning=row;assignForm.reset();assignForm.request_id=newRequestId()">补充归因</button><button v-if="section==='rewards' && ['pending','failed','revoke_pending'].includes(row.status) && permissions['rewards.retry']" class="mt-2 text-emerald-700" @click="router.post(`${base}/rewards/${row.public_id}/retry`,{}, {preserveScroll:true})">重试同步</button><div v-if="section==='payouts'" class="mt-2 flex flex-wrap gap-3"><a v-if="permissions['reports.export']" :href="`${base}/finance/payouts/${row.public_id}/csv`" class="text-emerald-700">导出明细</a><a v-if="row.has_proof" :href="`${base}/finance/payouts/${row.public_id}/proof`" class="text-emerald-700">付款凭证</a><button v-if="row.status==='draft'&&permissions['payouts.confirm']" class="text-emerald-700" @click="openAction(row,'paid')">记录已付款</button><button v-if="row.status==='draft'&&permissions['payouts.create']" class="text-amber-700" @click="openAction(row,'cancelled')">取消批次</button></div><div v-if="section==='risks'&&['open','reviewing'].includes(row.status)&&permissions['fraud.review']" class="mt-2 flex gap-3"><button class="text-emerald-700" @click="openAction(row,'approved')">通过审核</button><button class="text-red-700" @click="openAction(row,'rejected')">拒绝计佣</button></div></td></tr><tr v-if="!rows.data.length"><td colspan="5" class="p-12 text-center text-slate-400">暂无记录。完成订单归因后会自动显示。</td></tr></tbody></table></div>
   <nav class="flex flex-wrap gap-2"><Link v-for="(link,i) in rows.links" :key="i" :href="link.url||'#'" :class="['rounded-lg border px-3 py-2 text-sm',link.active?'bg-emerald-700 text-white':'bg-white',!link.url?'pointer-events-none opacity-40':'']"><span v-html="link.label"/></Link></nav>
  </div>
  <div v-if="selected" class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-5" @click.self="selected=null"><form class="w-full max-w-lg space-y-4 rounded-2xl bg-white p-6 shadow-xl" @submit.prevent="submitAction"><h2 class="text-lg font-bold">{{section==='risks'?'风险审核':action.action==='paid'?'记录外部付款':'取消结算批次'}}</h2><p class="text-sm text-slate-500">{{section==='risks'?'请填写审核依据，操作会保留审计记录。':action.action==='paid'?`请确认已在外部支付 ${selected.amount} ${selected.currency}。此操作记录付款结果。`:'取消后，批次中的分录恢复为可用。'}}</p><textarea v-if="section==='risks'" v-model="action.reason" required minlength="3" placeholder="审核原因" class="w-full rounded-xl border-slate-300"/><template v-if="section==='payouts'&&action.action==='paid'"><input v-model="action.reference" placeholder="付款参考号" class="w-full rounded-xl border-slate-300"><label class="block text-sm">付款凭证（PDF、PNG、JPG，最多 5 MB）<input type="file" accept=".pdf,.png,.jpg,.jpeg" class="mt-2 block w-full" @change="action.proof=($event.target as HTMLInputElement).files?.[0]??null"></label></template><p v-for="error in action.errors" :key="error" class="text-sm text-red-600">{{error}}</p><div class="flex justify-end gap-3"><button type="button" class="rounded-xl border px-4 py-2" @click="selected=null">返回</button><button :disabled="action.processing" class="rounded-xl bg-emerald-700 px-4 py-2 text-white">确认</button></div></form></div>
 <div v-if="assigning" class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-5"><form class="w-full max-w-lg space-y-4 rounded-2xl bg-white p-6" @submit.prevent="assignForm.post(`${base}/conversions/${assigning.public_id}/attribute`,{onSuccess:()=>assigning=null})"><h2 class="text-lg font-bold">补充归因 · {{assigning.label}}</h2><p class="text-sm text-slate-500">将重新读取 Shopify 订单并扣除已发生退款。操作会记录审核人及原因。</p><select v-model="assignForm.membership" required class="w-full rounded-xl border-slate-300"><option value="">选择推广者</option><option v-for="member in memberships" :key="member.public_id" :value="member.public_id">{{member.name}}</option></select><textarea v-model="assignForm.reason" required minlength="3" maxlength="1000" placeholder="填写补归因依据" class="w-full rounded-xl border-slate-300"/><p v-for="error in assignForm.errors" :key="error" class="text-red-700">{{error}}</p><div class="flex justify-end gap-4"><button type="button" @click="assigning=null">返回</button><button :disabled="assignForm.processing" class="rounded-xl bg-emerald-700 px-4 py-2 text-white">确认补归因</button></div></form></div></AppLayout>
</template>
