<script setup lang="ts">
import "../../../../shopify-apps/deco-referral/resources/admin/workspace.css";
import StatusBadge from "../../../../shopify-apps/deco-referral/resources/admin/StatusBadge.vue";
import { Head, Link, router, useForm } from '@inertiajs/vue3';
import { computed, ref } from 'vue';
import EmptyState from '../../Components/Feedback/EmptyState.vue';
import AppLayout from '../../Layouts/AppLayout.vue';
import RewardRuleEditor from './RewardRuleEditor.vue';

interface ProgramRule { scope: string; reference: string; label?:string; type: string; basis_points: number|null; amount_minor:number|null; exclude:boolean; fixed_mode:string }
interface RewardRule {type:string;basis_points:number|null;amount_minor:number|null;valid_days:number;scope:string;resource_ids:string[];resource_labels?:Record<string,string>}
interface Program { auto_invite:boolean; starts_at:string|null; ends_at:string|null; reward:RewardRule|null; milestones:{threshold:number;reward:RewardRule}[]; default_rule?: {commission_type:string;rate_basis_points:number|null;amount_minor:number|null}; rules:ProgramRule[]; public_id: string; name: string; type: string; status: string; attribution_model: string; attribution_window_days: number; hold_days: number; currency: string; memberships_count: number; coupon_enabled: boolean; customer_discount_type: string | null; customer_discount_rate_basis_points: number | null; customer_discount_amount_minor: number | null }
interface Membership { tier_key:string|null; labels:string[]; admin_notes:string|null; application:Record<string,unknown>|null; rejection_reason:string|null; commission_override:{commission_type:string;rate_basis_points:number|null;amount_minor:number|null;settings?:{fixed_mode:string}}|null; public_id: string; status: string; program: { public_id: string; name: string } | null; promoter: { public_id: string; display_name: string; email: string; type: string; status: string }; link: { url: string; code: string; status: string } | null; coupon: { code: string; status: string; last_error: string | null } | null }
const props = defineProps<{
    currency_decimals: number;
    organization: { id: number; name: string };
    store: { id: number; name: string; currency: string };
    section: 'overview' | 'programs' | 'promoters';
    settings: { affiliate_enabled: boolean; customer_referral_enabled: boolean };
    stats: { programs: number; active_programs: number; promoters: number; pending_memberships: number };
    programs: Program[];
    memberships: Membership[];
    permissions: { managePrograms: boolean; managePromoters: boolean; manageSettings: boolean };
}>();

const moneyFactor = 10 ** props.currency_decimals;
const moneyStep = 1 / moneyFactor;
const baseUrl = `/organizations/${props.organization.id}/stores/${props.store.id}/affiliate`;
const newReward=():RewardRule=>({type:'fixed',basis_points:1000,amount_minor:10*(10**props.currency_decimals),valid_days:30,scope:'all',resource_ids:[]});
const showProgramForm = ref(false);
const editingProgram=ref<string|null>(null);
const rulesProgram=ref<Program|null>(null);
const rulesForm=useForm({rules:[] as ProgramRule[]});
const catalog=ref<{id:string;name:string}[]>([]);
const ruleScope=ref("product");
const catalogTerm=ref("");
const selectedCatalog=ref("");
async function searchCatalog(){const response=await fetch(`${baseUrl}/catalog?scope=${ruleScope.value}&q=${encodeURIComponent(catalogTerm.value)}`,{headers:{Accept:"application/json"}});if(response.ok)catalog.value=(await response.json()).data;}
function openRules(program:Program){rulesProgram.value=program;rulesForm.rules=program.rules.map(r=>({...r}));searchCatalog();}
function addRule(){const item=catalog.value.find(x=>x.id===selectedCatalog.value);if(!item)return;rulesForm.rules.push({scope:ruleScope.value,reference:item.id,label:item.name,type:"percentage",basis_points:1200,amount_minor:null,exclude:false,fixed_mode:"order"});}
const localDate=(value:string|null)=>{if(!value)return '';const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);};
function editProgram(p:Program){editingProgram.value=p.public_id;showProgramForm.value=true;Object.assign(programForm,{auto_invite:p.auto_invite,starts_at:localDate(p.starts_at),ends_at:localDate(p.ends_at),reward:p.reward?JSON.parse(JSON.stringify(p.reward)):newReward(),milestones:JSON.parse(JSON.stringify(p.milestones??[])),name:p.name,type:p.type,attribution_model:p.attribution_model,attribution_window_days:p.attribution_window_days,hold_days:p.hold_days,coupon_enabled:p.coupon_enabled,customer_discount_type:p.customer_discount_type??"percentage",customer_discount_rate_basis_points:p.customer_discount_rate_basis_points??1000,customer_discount_amount_minor:p.customer_discount_amount_minor,commission_type:p.default_rule?.commission_type??"percentage",rate_basis_points:p.default_rule?.rate_basis_points??1000,amount_minor:p.default_rule?.amount_minor??null});}
const invitation=ref<{url:string;name:string}|null>(null);const inviteError=ref('');
async function inviteMember(member:Membership){
    inviteError.value='';
    try {
        const cookie=document.cookie.split('; ').find(value=>value.startsWith('XSRF-TOKEN='));
        const response=await fetch(`${baseUrl}/memberships/${member.public_id}/invite`,{method:'POST',credentials:'same-origin',headers:{Accept:'application/json','X-Requested-With':'XMLHttpRequest','X-XSRF-TOKEN':cookie?decodeURIComponent(cookie.slice('XSRF-TOKEN='.length)):''}});
        const data=await response.json();
        if(!response.ok)throw new Error(data.message??'邀请创建失败');
        invitation.value={url:data.url,name:member.promoter.display_name};
    }catch(e){inviteError.value=e instanceof Error?e.message:'邀请创建失败';}
}
function copyInvitation(){if(invitation.value)navigator.clipboard.writeText(invitation.value.url).catch(()=>inviteError.value='请选中链接手动复制。');}

const editingMember = ref<Membership|null>(null);
const memberForm = useForm({tier_key:'',labels:[] as string[],admin_notes:'',commission_override:null as Membership['commission_override']});
function editMember(member:Membership){editingMember.value=member;memberForm.tier_key=member.tier_key??'';memberForm.labels=[...member.labels];memberForm.admin_notes=member.admin_notes??'';memberForm.commission_override=member.commission_override?JSON.parse(JSON.stringify(member.commission_override)):null;}
const showPromoterForm = ref(false);
const settingsForm = useForm({ ...props.settings });
const programForm = useForm({ auto_invite:false,starts_at:'',ends_at:'', reward:newReward(),milestones:[] as {threshold:number;reward:RewardRule}[], name: '', type: 'affiliate', attribution_model: 'coupon_wins', attribution_window_days: 30, hold_days: 30, commission_type: 'percentage', rate_basis_points: 1000, amount_minor: null as number | null, coupon_enabled: true, customer_discount_type: 'percentage', customer_discount_rate_basis_points: 1000, customer_discount_amount_minor: null as number | null });
const importForm=useForm({program:props.programs[0]?.public_id??'',file:null as File|null});
const promoterForm = useForm({ display_name: '', email: '', type: 'affiliate', program_public_id: props.programs[0]?.public_id ?? '' });
const sectionTitle = computed(() => ({ overview: '推荐与联盟', programs: '推广计划', promoters: '推广者' })[props.section]);
const submitProgram = () => { programForm.transform(data=>({...data,starts_at:data.starts_at?new Date(data.starts_at).toISOString():null,ends_at:data.ends_at?new Date(data.ends_at).toISOString():null})); const options={preserveScroll:true,onSuccess:()=>{programForm.reset();showProgramForm.value=false;editingProgram.value=null;}};if(editingProgram.value)programForm.put(`${baseUrl}/programs/${editingProgram.value}`,options);else programForm.post(`${baseUrl}/programs`,options); };
const submitPromoter = () => promoterForm.post(`${baseUrl}/promoters`, { preserveScroll: true, onSuccess: () => { promoterForm.reset('display_name', 'email'); showPromoterForm.value = false; } });
const saveSettings = () => settingsForm.put(`${baseUrl}/settings`, { preserveScroll: true });
const syncCoupon = (membership: Membership) => router.post(`${baseUrl}/memberships/${membership.public_id}/sync-coupon`, {}, { preserveScroll: true });
const couponStatus = (status: string) => ({ active: '已生效', scheduled: '未到生效时间', disabled: '已停用', sync_pending: '等待同步', provisioning: '等待创建', enable_pending: '等待启用', disable_pending: '等待停用' }[status] ?? status);
const typeLabel = (value: string) => ({ affiliate: '联盟客', influencer: '达人', ambassador: '品牌大使', advocate: '顾客推荐', partner: '合作伙伴' }[value] ?? value);
const transitionProgram = (program: Program, action: 'activate' | 'pause') => router.post(`${baseUrl}/programs/${program.public_id}/transition`, { action }, { preserveScroll: true });
const rejectingMember = ref<Membership|null>(null);
const rejectionForm = useForm({action:'reject',reason:''});
const transitionMembership = (membership: Membership, action: 'approve' | 'suspend' | 'waitlist') => router.post(`${baseUrl}/memberships/${membership.public_id}/transition`, { action }, { preserveScroll: true });
</script>

<template>
    <Head :title="sectionTitle" />
    <AppLayout :breadcrumbs="[{ label: '推荐与联盟' }, ...(section === 'overview' ? [] : [{ label: sectionTitle }])]"><div class="affiliate-workspace">
        <div class="space-y-6">
            <header class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
                <div><p class="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-700">{{ store.name }}</p><h1 class="mt-1 text-2xl font-bold text-slate-950">{{ sectionTitle }}</h1><p class="mt-2 text-sm text-slate-500">管理推广计划、合作伙伴和推荐奖励。</p></div>
                <button v-if="section === 'programs' && permissions.managePrograms" class="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white" @click="editingProgram=null;programForm.reset();showProgramForm=!showProgramForm">新建计划</button>
                <button v-if="section === 'promoters' && permissions.managePromoters && programs.length" class="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white" @click="showPromoterForm = !showPromoterForm">添加推广者</button>
            </header>

            <p v-if="inviteError" class="text-red-700">{{inviteError}}</p><div v-if="invitation" class="space-y-2 rounded-xl border bg-white p-4"><p>{{invitation.name}} 的邀请链接，七天有效。请私下转交给本人。</p><input :value="invitation.url" readonly class="w-full rounded-lg border-slate-300" @focus="($event.target as HTMLInputElement).select()"><button class="text-emerald-700" @click="copyInvitation">复制邀请</button><button class="ml-4 text-slate-500" @click="invitation=null">收起</button></div>
            <nav class="flex gap-2 rounded-2xl border border-slate-200 bg-white p-2">
                <Link v-for="tab in [{ key: 'overview', label: '概览', path: '' }, { key: 'programs', label: '推广计划', path: '/programs' }, { key: 'promoters', label: '推广者', path: '/promoters' }]" :key="tab.key" :href="`${baseUrl}${tab.path}`" class="rounded-xl px-4 py-2 text-sm font-semibold" :class="section === tab.key ? 'bg-slate-950 text-white' : 'text-slate-600 hover:bg-slate-100'">{{ tab.label }}</Link>
            </nav>

            <template v-if="section === 'overview'">
                <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
                    <article v-for="item in [{ label: '推广计划', value: stats.programs }, { label: '已启用计划', value: stats.active_programs }, { label: '推广者', value: stats.promoters }, { label: '待审核', value: stats.pending_memberships }]" :key="item.label" class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-sm text-slate-500">{{ item.label }}</p><p class="mt-2 text-3xl font-bold text-slate-950">{{ item.value }}</p></article>
                </div>
                <section class="rounded-2xl border border-slate-200 bg-white p-6">
                    <h2 class="text-lg font-semibold text-slate-950">店铺功能</h2><p class="mt-1 text-sm text-slate-500">先启用联盟营销；顾客推荐可在联盟账本稳定后开启。</p>
                    <div class="mt-5 grid gap-4 sm:grid-cols-2">
                        <label class="flex items-center justify-between rounded-xl border border-slate-200 p-4"><span><b class="block text-sm">联盟营销</b><small class="text-slate-500">推广计划、佣金与结算</small></span><input v-model="settingsForm.affiliate_enabled" type="checkbox" class="rounded border-slate-300 text-emerald-600" :disabled="!permissions.manageSettings"></label>
                        <label class="flex items-center justify-between rounded-xl border border-slate-200 p-4"><span><b class="block text-sm">顾客推荐</b><small class="text-slate-500">好友优惠与推荐奖励</small></span><input v-model="settingsForm.customer_referral_enabled" type="checkbox" class="rounded border-slate-300 text-emerald-600" :disabled="!permissions.manageSettings"></label>
                    </div>
                    <button v-if="permissions.manageSettings" class="mt-5 rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50" :disabled="settingsForm.processing" @click="saveSettings">保存设置</button>
                </section>
            </template>

            <template v-else-if="section === 'programs'">
                <form v-if="showProgramForm" class="grid gap-4 rounded-2xl border border-slate-200 bg-white p-6 sm:grid-cols-2" @submit.prevent="submitProgram">
                    <label class="sm:col-span-2"><span class="text-sm font-medium">计划名称</span><input v-model="programForm.name" class="mt-1 w-full rounded-xl border-slate-300" required maxlength="120"></label>
                    <label><span class="text-sm font-medium">类型</span><select v-model="programForm.type" :disabled="!!editingProgram" class="mt-1 w-full rounded-xl border-slate-300"><option value="affiliate">联盟客</option><option value="influencer">达人</option><option value="ambassador">品牌大使</option><option value="advocate">顾客推荐</option><option value="partner">合作伙伴</option></select></label>
                    <label><span class="text-sm font-medium">归因方式</span><select v-model="programForm.attribution_model" class="mt-1 w-full rounded-xl border-slate-300"><option value="coupon_wins">优惠码优先</option><option value="last_click">最后点击</option><option value="first_click">首次点击</option></select></label>
                    <label><span class="text-sm font-medium">归因窗口（天）</span><input v-model.number="programForm.attribution_window_days" type="number" min="1" max="90" class="mt-1 w-full rounded-xl border-slate-300"></label>
                    <label><span class="text-sm font-medium">等待期（天）</span><input v-model.number="programForm.hold_days" type="number" min="0" max="90" class="mt-1 w-full rounded-xl border-slate-300"></label>
                    <label><span class="text-sm font-medium">开始时间（当前设备时区，可留空）</span><input v-model="programForm.starts_at" type="datetime-local" class="mt-1 w-full rounded-xl border-slate-300"></label><label><span class="text-sm font-medium">结束时间（当前设备时区，可留空）</span><input v-model="programForm.ends_at" type="datetime-local" class="mt-1 w-full rounded-xl border-slate-300"></label>
                    <label v-if="programForm.type!=='advocate'"><span class="text-sm font-medium">佣金类型</span><select v-model="programForm.commission_type" class="mt-1 w-full rounded-xl border-slate-300"><option value="percentage">百分比</option><option value="fixed">固定金额</option></select></label>
                    <label v-if="programForm.type!=='advocate' && programForm.commission_type === 'percentage'"><span class="text-sm font-medium">佣金比例（%）</span><input :value="programForm.rate_basis_points / 100" type="number" step="0.01" min="0.01" max="100" class="mt-1 w-full rounded-xl border-slate-300" @input="programForm.rate_basis_points = Math.round(Number(($event.target as HTMLInputElement).value) * 100)"></label>
                    <label v-else-if="programForm.type!=='advocate'"><span class="text-sm font-medium">固定金额（{{ store.currency }}）</span><input :value="(programForm.amount_minor ?? 0) / moneyFactor" type="number" :step="moneyStep" :min="moneyStep" class="mt-1 w-full rounded-xl border-slate-300" @input="programForm.amount_minor = Math.round(Number(($event.target as HTMLInputElement).value) * moneyFactor)"></label>
                    <div v-if="programForm.type==='advocate'" class="space-y-4 sm:col-span-2"><h3 class="font-semibold">推荐人奖励</h3><label class="flex gap-2 text-sm"><input v-model="programForm.auto_invite" type="checkbox">购后自动邀请（仅同意营销邮件的顾客；还需启用“购后邀请”消息模板）</label><p class="text-sm text-slate-500">好友订单通过新客核验与等待期后发放一次性优惠码，仅推荐人本人可以使用；不产生现金佣金。</p><RewardRuleEditor v-model="programForm.reward" :base="baseUrl" :currency="store.currency" :decimals="currency_decimals"/><details><summary class="cursor-pointer font-semibold">累计推荐里程碑</summary><div v-for="(milestone,index) in programForm.milestones" :key="index" class="mt-4 space-y-3"><div class="flex items-center justify-between"><label class="text-sm">有效推荐订单数 <input v-model.number="milestone.threshold" type="number" min="1" max="10000" class="w-24 rounded-xl border-slate-300"></label><button type="button" class="text-red-700" @click="programForm.milestones.splice(index,1)">移除</button></div><RewardRuleEditor v-model="milestone.reward" :base="baseUrl" :currency="store.currency" :decimals="currency_decimals"/></div><button v-if="programForm.milestones.length<20" type="button" class="mt-3 rounded-xl border px-3 py-2 text-sm" @click="programForm.milestones.push({threshold:3,reward:newReward()})">添加里程碑</button></details></div>
                    <label class="flex items-center gap-3 rounded-xl border border-slate-200 p-3 sm:col-span-2"><input v-model="programForm.coupon_enabled" type="checkbox" class="rounded border-slate-300 text-emerald-600"><span><b class="block text-sm">生成顾客优惠码</b><small class="text-slate-500">佣金比例与顾客优惠分别设置</small></span></label>
                    <template v-if="programForm.coupon_enabled">
                        <label><span class="text-sm font-medium">顾客优惠类型</span><select v-model="programForm.customer_discount_type" class="mt-1 w-full rounded-xl border-slate-300"><option value="percentage">百分比</option><option value="fixed">固定金额</option><option value="free_shipping">免运费</option></select></label>
                        <label v-if="programForm.customer_discount_type === 'percentage'"><span class="text-sm font-medium">顾客优惠（%）</span><input :value="programForm.customer_discount_rate_basis_points / 100" type="number" step="0.01" min="0.01" max="100" class="mt-1 w-full rounded-xl border-slate-300" @input="programForm.customer_discount_rate_basis_points = Math.round(Number(($event.target as HTMLInputElement).value) * 100)"></label>
                        <label v-else-if="programForm.customer_discount_type==='fixed'"><span class="text-sm font-medium">顾客优惠金额（{{ store.currency }}）</span><input :value="(programForm.customer_discount_amount_minor ?? 0) / moneyFactor" type="number" :step="moneyStep" :min="moneyStep" class="mt-1 w-full rounded-xl border-slate-300" @input="programForm.customer_discount_amount_minor = Math.round(Number(($event.target as HTMLInputElement).value) * moneyFactor)"></label>
                    </template>
                    <div class="sm:col-span-2"><button class="rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white" :disabled="programForm.processing">{{editingProgram?'保存计划':'创建计划'}}</button><p v-if="Object.keys(programForm.errors).length" class="mt-2 text-sm text-rose-600">{{ Object.values(programForm.errors)[0] }}</p></div>
                </form>
                <EmptyState v-if="!programs.length" title="还没有推广计划" description="创建第一个计划，设置归因窗口、等待期和默认佣金。" icon="campaign" />
                <div v-else class="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table class="w-full min-w-[760px] text-left text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4">计划</th><th class="p-4">归因</th><th class="p-4">等待期</th><th class="p-4">推广者</th><th class="p-4">状态</th><th v-if="permissions.managePrograms" class="p-4">操作</th></tr></thead><tbody><tr v-for="program in programs" :key="program.public_id" class="border-t border-slate-100"><td class="p-4"><b>{{ program.name }}</b><span class="ml-2 text-xs text-slate-500">{{ typeLabel(program.type) }}</span></td><td class="p-4">{{ ({coupon_wins:'优惠码优先',last_click:'最后点击',first_click:'首次点击'} as Record<string,string>)[program.attribution_model] ?? program.attribution_model }} · {{ program.attribution_window_days }} 天</td><td class="p-4">{{ program.hold_days }} 天</td><td class="p-4">{{ program.memberships_count }}</td><td class="p-4"><StatusBadge :status="program.status" /></td><td v-if="permissions.managePrograms" class="p-4"><button class="mr-3 font-semibold text-emerald-700" @click="editProgram(program)">编辑</button><button class="mr-3 font-semibold text-emerald-700" @click="openRules(program)">商品规则</button><button v-if="program.status !== 'active'" class="font-semibold text-emerald-700" @click="transitionProgram(program, 'activate')">启用</button><button v-else class="font-semibold text-amber-700" @click="transitionProgram(program, 'pause')">暂停</button></td></tr></tbody></table></div>
            </template>

            <template v-else>
                <form v-if="showPromoterForm" class="grid gap-4 rounded-2xl border border-slate-200 bg-white p-6 sm:grid-cols-2" @submit.prevent="submitPromoter">
                    <label><span class="text-sm font-medium">名称</span><input v-model="promoterForm.display_name" class="mt-1 w-full rounded-xl border-slate-300" required></label>
                    <label><span class="text-sm font-medium">邮箱</span><input v-model="promoterForm.email" type="email" class="mt-1 w-full rounded-xl border-slate-300" required></label>
                    <label><span class="text-sm font-medium">身份</span><select v-model="promoterForm.type" class="mt-1 w-full rounded-xl border-slate-300"><option value="affiliate">联盟客</option><option value="influencer">达人</option><option value="ambassador">品牌大使</option><option value="advocate">顾客推荐</option><option value="partner">合作伙伴</option></select></label>
                    <label><span class="text-sm font-medium">加入计划</span><select v-model="promoterForm.program_public_id" class="mt-1 w-full rounded-xl border-slate-300"><option v-for="program in programs" :key="program.public_id" :value="program.public_id">{{ program.name }}</option></select></label>
                    <div class="sm:col-span-2"><button class="rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white" :disabled="promoterForm.processing">添加推广者</button><p v-if="Object.keys(promoterForm.errors).length" class="mt-2 text-sm text-rose-600">{{ Object.values(promoterForm.errors)[0] }}</p></div>
                </form>
                <details v-if="permissions.managePromoters && programs.length" class="rounded-2xl border bg-white p-5"><summary class="cursor-pointer font-semibold">从 CSV 批量导入</summary><form class="mt-4 flex flex-wrap items-end gap-4" @submit.prevent="importForm.post(`${baseUrl}/promoters/import`,{forceFormData:true})"><p class="w-full text-sm text-slate-500">文件表头为 name,email，最多 500 行。导入后等待审核；同一计划的重复邮箱会跳过。</p><select v-model="importForm.program" class="rounded-xl border-slate-300"><option v-for="program in programs" :key="program.public_id" :value="program.public_id">{{program.name}}</option></select><input type="file" accept=".csv,text/csv" required @change="importForm.file=($event.target as HTMLInputElement).files?.[0]??null"><button :disabled="importForm.processing" class="rounded-xl bg-emerald-700 px-4 py-2 text-white">导入为待审核</button><p v-for="error in importForm.errors" :key="error" class="w-full text-red-700">{{error}}</p></form></details>
                <EmptyState v-if="!memberships.length" title="还没有推广者" :description="programs.length ? '添加推广者并分配到当前店铺的推广计划。' : '请先创建推广计划，再添加推广者。'" icon="users" />
                <div v-else class="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table class="w-full min-w-[900px] text-left text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4">推广者</th><th class="p-4">计划</th><th class="p-4">身份</th><th class="p-4">推广资产</th><th class="p-4">状态</th><th v-if="permissions.managePromoters" class="p-4">操作</th></tr></thead><tbody><tr v-for="membership in memberships" :key="membership.public_id" class="border-t border-slate-100"><td class="p-4"><b>{{ membership.promoter.display_name }}</b><p class="text-xs text-slate-500">{{ membership.promoter.email }}</p></td><td class="p-4">{{ membership.program?.name }}</td><td class="p-4">{{ typeLabel(membership.promoter.type) }}</td><td class="p-4"><template v-if="membership.link"><a :href="membership.link.url" target="_blank" rel="noreferrer" class="block max-w-64 truncate font-medium text-emerald-700">{{ membership.link.url }}</a><p class="mt-1 text-xs text-slate-500">优惠码 {{ membership.coupon?.code }} · {{ membership.coupon ? couponStatus(membership.coupon.status) : '未配置' }}</p><p v-if="membership.coupon?.last_error" class="mt-1 max-w-64 text-xs text-red-600">{{ membership.coupon.last_error }}</p><button v-if="membership.coupon && permissions.managePromoters" class="mt-1 text-xs font-medium text-emerald-700" @click="syncCoupon(membership)">同步 Shopify 优惠码</button></template><span v-else class="text-slate-400">审核后生成</span></td><td class="p-4"><StatusBadge :status="membership.status" :label="membership.status==='pending'?'待审核':undefined" /></td><td v-if="permissions.managePromoters" class="p-4"><button v-if="['pending','waitlisted'].includes(membership.status)" class="mr-3 text-emerald-700" @click="inviteMember(membership)">邀请加入</button><button class="mr-3 text-emerald-700" @click="editMember(membership)">编辑资料</button><button v-if="membership.status !== 'approved'" class="font-semibold text-emerald-700" @click="transitionMembership(membership, 'approve')">通过</button><button v-else class="font-semibold text-amber-700" @click="transitionMembership(membership, 'suspend')">暂停</button><button v-if="membership.status === 'pending'" class="ml-3 text-amber-700" @click="transitionMembership(membership, 'waitlist')">候补</button><button v-if="['pending','waitlisted'].includes(membership.status)" class="ml-3 text-red-700" @click="rejectingMember=membership;rejectionForm.reset()">拒绝</button></td></tr></tbody></table></div>
            </template>
        </div>
        <div v-if="rulesProgram" class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-5" @click.self="rulesProgram=null"><form class="max-h-[85vh] w-full max-w-3xl space-y-4 overflow-auto rounded-2xl bg-white p-6" @submit.prevent="rulesForm.put(`${baseUrl}/programs/${rulesProgram.public_id}/rules`,{onSuccess:()=>rulesProgram=null})"><h2 class="text-lg font-bold">{{rulesProgram.name}} · 商品佣金规则</h2><p class="text-sm text-slate-500">商品规格优先于商品，商品优先于系列；未匹配时使用计划默认佣金。</p><div class="flex flex-wrap gap-2"><select v-model="ruleScope" class="rounded-lg border-slate-300" @change="searchCatalog"><option value="product">商品</option><option value="variant">商品规格</option><option value="collection">系列</option></select><input v-model="catalogTerm" placeholder="按名称搜索" class="rounded-lg border-slate-300"><button type="button" class="rounded-lg border px-3" @click="searchCatalog">搜索</button><select v-model="selectedCatalog" class="max-w-xs rounded-lg border-slate-300"><option value="">选择已同步的商品</option><option v-for="item in catalog" :key="item.id" :value="item.id">{{item.name}}</option></select><button type="button" class="rounded-lg border px-3" @click="addRule">添加</button></div><div v-for="(rule,index) in rulesForm.rules" :key="index" class="space-y-2 rounded-xl border p-4"><div class="flex justify-between"><b>{{rule.label||'已选商品'}}</b><button type="button" class="text-red-700" @click="rulesForm.rules.splice(index,1)">移除</button></div><div class="flex flex-wrap items-center gap-3"><label class="text-sm"><input v-model="rule.exclude" type="checkbox"> 排除计佣</label><select v-model="rule.type" class="rounded-lg border-slate-300"><option value="percentage">百分比佣金</option><option value="fixed">固定佣金</option></select><label v-if="rule.type==='percentage'" class="text-sm">比例 % <input :value="(rule.basis_points??0)/100" type="number" step="0.01" min="0" max="100" class="w-24 rounded-lg border-slate-300" @input="rule.basis_points=Math.round(Number(($event.target as HTMLInputElement).value)*100)"></label><template v-else><label class="text-sm">金额 {{store.currency}} <input :value="(rule.amount_minor??0)/moneyFactor" type="number" :step="moneyStep" min="0" class="w-24 rounded-lg border-slate-300" @input="rule.amount_minor=Math.round(Number(($event.target as HTMLInputElement).value)*moneyFactor)"></label><select v-model="rule.fixed_mode" class="rounded-lg border-slate-300"><option value="order">每单一次</option><option value="item">每件商品</option></select></template></div></div><p v-for="error in rulesForm.errors" :key="error" class="text-sm text-red-600">{{error}}</p><div class="flex justify-end gap-3"><button type="button" class="rounded-xl border px-4 py-2" @click="rulesProgram=null">返回</button><button :disabled="rulesForm.processing" class="rounded-xl bg-emerald-700 px-4 py-2 text-white">保存规则</button></div></form></div>
        <div v-if="rejectingMember" class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-5"><form class="w-full max-w-lg space-y-4 rounded-2xl bg-white p-6" @submit.prevent="rejectionForm.post(`${baseUrl}/memberships/${rejectingMember.public_id}/transition`,{onSuccess:()=>rejectingMember=null})"><h2 class="text-lg font-bold">拒绝申请 · {{rejectingMember.promoter.display_name}}</h2><label class="block">拒绝原因<textarea v-model="rejectionForm.reason" required minlength="3" maxlength="1000" class="mt-2 w-full rounded-xl border-slate-300" /></label><p v-for="error in rejectionForm.errors" :key="error" class="text-red-700">{{error}}</p><div class="flex justify-end gap-3"><button type="button" @click="rejectingMember=null">返回</button><button :disabled="rejectionForm.processing" class="rounded-xl bg-red-700 px-4 py-2 text-white">确认拒绝</button></div></form></div>
        <div v-if="editingMember" class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-5"><form class="max-h-[85vh] w-full max-w-xl space-y-4 overflow-auto rounded-2xl bg-white p-6" @submit.prevent="memberForm.put(`${baseUrl}/memberships/${editingMember.public_id}`,{onSuccess:()=>editingMember=null})"><h2 class="text-lg font-bold">{{editingMember.promoter.display_name}} · 编辑资料</h2><label class="block">等级<input v-model="memberForm.tier_key" maxlength="64" class="mt-1 w-full rounded-xl border-slate-300"></label><label class="block">标签（逗号分隔）<input :value="memberForm.labels.join(', ')" class="mt-1 w-full rounded-xl border-slate-300" @input="memberForm.labels=($event.target as HTMLInputElement).value.split(',').map(x=>x.trim()).filter(Boolean)"></label><label class="block">内部备注<textarea v-model="memberForm.admin_notes" maxlength="4000" class="mt-1 w-full rounded-xl border-slate-300" /></label><label v-if="editingMember.promoter.type!=='advocate'" class="flex gap-2"><input type="checkbox" :checked="!!memberForm.commission_override" @change="memberForm.commission_override=($event.target as HTMLInputElement).checked?{commission_type:'percentage',rate_basis_points:1000,amount_minor:null,settings:{fixed_mode:'order'}}:null">单独设置佣金</label><div v-if="editingMember.promoter.type!=='advocate' && memberForm.commission_override" class="space-y-3"><select v-model="memberForm.commission_override.commission_type" class="rounded-xl border-slate-300"><option value="percentage">百分比</option><option value="fixed">固定金额</option></select><label v-if="memberForm.commission_override.commission_type==='percentage'" class="block">比例 % <input :value="(memberForm.commission_override.rate_basis_points??0)/100" type="number" min="0" max="100" step="0.01" class="rounded-xl border-slate-300" @input="memberForm.commission_override.rate_basis_points=Math.round(Number(($event.target as HTMLInputElement).value)*100)"></label><label v-else class="block">每单金额 {{store.currency}} <input :value="(memberForm.commission_override.amount_minor??0)/moneyFactor" type="number" min="0" :step="moneyStep" class="rounded-xl border-slate-300" @input="memberForm.commission_override.amount_minor=Math.round(Number(($event.target as HTMLInputElement).value)*moneyFactor)"></label></div><details v-if="editingMember.application"><summary>申请资料</summary><dl class="mt-3 space-y-2"><div v-for="(value,key) in editingMember.application" :key="key"><dt class="text-sm text-slate-500">{{key}}</dt><dd class="break-words">{{value}}</dd></div></dl></details><p v-if="editingMember.rejection_reason">拒绝原因：{{editingMember.rejection_reason}}</p><p v-for="error in memberForm.errors" :key="error" class="text-red-700">{{error}}</p><div class="flex justify-end gap-3"><button type="button" @click="editingMember=null">返回</button><button :disabled="memberForm.processing" class="rounded-xl bg-emerald-700 px-4 py-2 text-white">保存资料</button></div></form></div>
    </div></AppLayout>
</template>
