<script setup lang="ts">
import {ref,computed} from 'vue';
interface Reward {type:string;basis_points:number|null;amount_minor:number|null;valid_days:number;scope:string;resource_ids:string[];resource_labels?:Record<string,string>}
const props=defineProps<{modelValue:Reward;base:string;currency:string;decimals:number}>();
const emit=defineEmits<{(e:'update:modelValue',value:Reward):void}>();
const term=ref('');const results=ref<{id:string;name:string}[]>([]);const error=ref('');
const factor=computed(()=>10**props.decimals);
const change=(patch:Partial<Reward>)=>emit('update:modelValue',{...props.modelValue,...patch});
async function search(){error.value='';try{const r=await fetch(`${props.base}/catalog?scope=${props.modelValue.scope}&q=${encodeURIComponent(term.value)}`,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error();results.value=(await r.json()).data;}catch{error.value='商品列表加载失败，请重试。';}}
function toggle(item:{id:string;name:string}){const ids=props.modelValue.resource_ids.includes(item.id)?props.modelValue.resource_ids.filter(id=>id!==item.id):[...props.modelValue.resource_ids,item.id];change({resource_ids:ids,resource_labels:{...props.modelValue.resource_labels,[item.id]:item.name}});}
</script>
<template><div class="space-y-3 rounded-xl border border-slate-200 p-4"><div class="grid gap-3 sm:grid-cols-3"><label class="text-sm">奖励类型<select :value="modelValue.type" class="mt-1 w-full rounded-xl border-slate-300" @change="change({type:($event.target as HTMLSelectElement).value})"><option value="fixed">固定金额优惠码</option><option value="percentage">百分比优惠码</option><option value="free_shipping">免运费码</option></select></label><label v-if="modelValue.type==='percentage'" class="text-sm">优惠比例 %<input :value="(modelValue.basis_points??0)/100" type="number" min="0.01" max="100" step="0.01" class="mt-1 w-full rounded-xl border-slate-300" @input="change({basis_points:Math.round(Number(($event.target as HTMLInputElement).value)*100)})"></label><label v-else-if="modelValue.type==='fixed'" class="text-sm">金额 {{currency}}<input :value="(modelValue.amount_minor??0)/factor" type="number" :min="1/factor" :step="1/factor" class="mt-1 w-full rounded-xl border-slate-300" @input="change({amount_minor:Math.round(Number(($event.target as HTMLInputElement).value)*factor)})"></label><label class="text-sm">发放后有效天数<input :value="modelValue.valid_days" type="number" min="1" max="365" class="mt-1 w-full rounded-xl border-slate-300" @input="change({valid_days:Number(($event.target as HTMLInputElement).value)})"></label></div><template v-if="modelValue.type!=='free_shipping'"><label class="block text-sm">适用范围<select :value="modelValue.scope" class="mt-1 w-full rounded-xl border-slate-300" @change="change({scope:($event.target as HTMLSelectElement).value,resource_ids:[]});results=[]"><option value="all">全部商品</option><option value="product">指定商品</option><option value="collection">指定系列</option></select></label><div v-if="modelValue.scope!=='all'" class="space-y-3"><div class="flex gap-2"><input v-model="term" placeholder="搜索本店商品或系列" class="w-full rounded-xl border-slate-300"><button type="button" class="shrink-0 rounded-xl border px-3" @click="search">搜索</button></div><div class="max-h-40 overflow-auto"><label v-for="item in results" :key="item.id" class="block py-1 text-sm"><input type="checkbox" :checked="modelValue.resource_ids.includes(item.id)" @change="toggle(item)"> {{item.name}}</label></div><p class="text-sm text-slate-500">已选 {{modelValue.resource_ids.length}} 项</p><button v-for="id in modelValue.resource_ids" :key="id" type="button" class="mr-2 rounded-lg bg-slate-100 px-2 py-1 text-sm" @click="change({resource_ids:modelValue.resource_ids.filter(x=>x!==id)})">{{modelValue.resource_labels?.[id]??'已选项目'}} ×</button><p v-if="error" class="text-sm text-red-700">{{error}}</p></div></template></div></template>
