<script setup lang="ts">
import { Head, Link } from '@inertiajs/vue3'; import AppLayout from '../../Layouts/AppLayout.vue';
interface Level { id:number; available:number; location:{id:number;name:string}|null }
interface Variant { id:number; title:string; sku:string|null; price:string; inventory_item:{levels:Level[]}|null }
interface Product { id:number; title:string; handle:string; status:string; vendor:string|null; product_type:string|null; description:string|null; synced_at:string|null; variants:Variant[] }
defineProps<{product:Product}>();
const statusLabel = (value:string) => ({active:'销售中',draft:'草稿',archived:'已归档'}[value] ?? value);
const price = (value:string) => Number(value).toFixed(2);
</script>
<template><Head :title="product.title"/><AppLayout :breadcrumbs="[{label:'业务中心'},{label:'商品管理',href:'/products'},{label:product.title}]"><div class="mx-auto max-w-6xl space-y-6"><Link href="/products" class="text-sm font-semibold text-slate-500 hover:text-emerald-700">← 返回商品列表</Link><header><p class="text-sm font-semibold text-emerald-700">Shopify 商品</p><h1 class="mt-1 text-3xl font-semibold text-slate-950">{{ product.title }}</h1><p class="mt-2 font-mono text-sm text-slate-400">{{ product.handle }}</p></header><section class="grid gap-4 sm:grid-cols-3"><div v-for="item in [['状态',statusLabel(product.status)],['品牌',product.vendor||'—'],['商品类型',product.product_type||'—']]" :key="String(item[0])" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wider text-slate-400">{{ item[0] }}</p><p class="mt-2 font-semibold text-slate-900">{{ item[1] }}</p></div></section><section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-6 py-5"><h2 class="font-semibold text-slate-950">商品变体</h2><p class="mt-1 text-sm text-slate-500">价格、SKU 与各地点可用库存。</p></div><div class="divide-y divide-slate-100"><article v-for="variant in product.variants" :key="variant.id" class="grid gap-4 px-6 py-5 md:grid-cols-[minmax(0,1fr)_160px_180px]"><div><p class="font-semibold text-slate-900">{{ variant.title }}</p><p class="mt-1 font-mono text-xs text-slate-400">SKU {{ variant.sku || '—' }}</p></div><p class="font-semibold text-slate-900">{{ price(variant.price) }}</p><div><p v-if="variant.inventory_item?.levels.length" v-for="level in variant.inventory_item.levels" :key="level.id" class="text-sm text-slate-600">{{ level.location?.name || '未知地点' }}：<b>{{ level.available }}</b></p><p v-else class="text-sm text-slate-400">暂无库存数据</p></div></article></div></section></div></AppLayout></template>
