client_id = "030f66008921f9d200ac057ef03fa163"
name = "Deco-学生优惠"
handle = "deco-student-discount"
application_url = "https://admin.decomkt.com/shopify-app/student-discounts"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "https://admin.decomkt.com/api/shopify-app/webhooks"

[[webhooks.subscriptions]]
topics = [ "app/scopes_update" ]
uri = "https://admin.decomkt.com/api/shopify-app/webhooks"

[access_scopes]
scopes = "read_discounts,write_discounts,read_products,write_app_proxy"
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://admin.decomkt.com/api/shopify-app/auth/callback" ]

[app_proxy]
url = "https://admin.decomkt.com/api/shopify-app/student-discounts/proxy"
prefix = "apps"
subpath = "deco-student-discount"
